- name: Install edx_ansible
  hosts: all
  become: True
  gather_facts: True
  vars:
    serial_count: 1
    ansible_python_interpreter: "{{ python_3_path }}"
  serial: "{{ serial_count }}"
  roles:
    - common
    - edx_ansible
